### PR TITLE
Use external cisagov/provisionaccount-role-tf-module

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##
This PR removes the internal `provisionaccount-role-tf-module` code and replaces it by using the new external [`cisagov/provisionaccount-role-tf-module`](https://github.com/cisagov/provisionaccount-role-tf-module).

## 💭 Motivation and Context ##
Now that [`cisagov/provisionaccount-role-tf-module`](https://github.com/cisagov/provisionaccount-role-tf-module) exists, there is no need for the internal `provisionaccount-role-tf-module` module in this repo. 

## 🧪 Testing ##
I ran `terraform init --upgrade` (to pick up the new external Terraform module) followed by `terraform apply` in several of the subdirectories (`audit`, `dns`, and `users`) and verified that Terraform did not want to make any changes (as expected).

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
* [x] Tests have been added and/or modified to cover the changes in this PR.
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
This looks great, although it would have been better to preserve history when extracting the Terraform role.  `git subtree` and `git filter-branch` are made for this sort of thing.  See, for instance, [this link](https://cjohansen.no/git-subtree-multiple-dirs/).

**Comment by jsf9k** [comment]
Also, you left the checkbox "Tests have been added and/or modified to cover the changes in this PR."  I don't see any tests added.  If this is the case then that checkbox should have been removed, not simply checked off as an empty task.

**Comment by mcdonnnj** [comment]
Adding feedback about the PR template: there are no TODOs for this PR, so I believe that checkbox should have been removed.

**Review by mcdonnnj — APPROVED** [review]
LGTM ✅ Thanks for breaking this out into its own project.

**Comment by dav3r** [comment]
> This looks great, although it would have been better to preserve history when extracting the Terraform role. `git subtree` and `git filter-branch` are made for this sort of thing. See, for instance, [this link](https://cjohansen.no/git-subtree-multiple-dirs/).

100% agree! Mea culpa.

**Comment by dav3r** [comment]
Thanks also @jsf9k and @mcdonnnj for the reminders to remove the checklist items that don't apply. 👍

**Pull request merged**
